---
- hosts: localhost
  connection: local
  become: True
  become_user: ec2-user
  tasks:
    - name: Add redis container
      shell: docker pull redis
    - name: Add docker-compose
      shell: sudo curl -L "https://github.com/docker/compose/releases/download/1.22.0/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
    - name: Apply execute permissions
      shell: sudo chmod +x /usr/local/bin/docker-compose
    - name: Start container
      shell: docker-compose up -d